name: Bug Report
description: "Submit an issue related to the Inertia Laravel adapter."
body:
  - type: markdown
    attributes:
      value: "Please read [our full contribution guide](https://laravel.com/docs/contributions#bug-reports) before submitting bug reports related to the Inertia Laravel adapter."
  - type: input
    attributes:
      label: "PHP package version"
      description: Provide the version of `inertiajs/inertia-laravel` you are using.
      placeholder: 2.0.0
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Inertia adapter(s) affected (if any)
      description: Select any frontend adapters involved in this issue, if relevant.
      options:
        - label: React
        - label: Vue 3
        - label: Svelte
        - label: Not Applicable
  - type: textarea
    attributes:
      label: Backend stack
      description: Provide details such as Laravel version, PHP version, and any relevant backend environment info.
      placeholder: |
        Laravel 12.x
        PHP 8.4
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the problem
      description: Explain the behavior you're seeing that you think is a bug, and describe how you expect it to behave instead.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Provide clear steps to reproduce the issue. Include a minimal code example that clearly shows the problem.
    validations:
      required: true
